name: Build Apk
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to latest version

    - name: Sign with debug key
      run: |
        sed -i "19i signingConfig signingConfigs.debug" ./app/build.gradle
        curl -so- https://raw.githubusercontent.com/artem-zinnatullin/RxJavaProGuardRules/master/rxjava-proguard-rules/proguard-rules.txt | tee -a ./app/proguard-rules.pro
        cat ./app/proguard-rules.pro

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Updated to latest version
      with:
        java-version: '11'
        distribution: 'temurin' # Use 'temurin' for latest support
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Get App Version Name
      id: version
      run: echo "app_version=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\([0-9.]*\)\".*/\1/p')" >> $GITHUB_ENV

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk game-unlocker-v${{ env.app_version }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3 # Updated to v3
      with:
        name: Game Unlocker
        path: game-unlocker-v${{ env.app_version }}.apk

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1 # Replace deprecated create-release@v1
      with:
        artifacts: game-unlocker-v${{ env.app_version }}.apk
        tag: ${{ env.app_version }}
        name: Game Unlocker v${{ env.app_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
